#
# $Id$
#
# Simple language definition for unit testing.
#
# This definition tests the use of actions for rules.
# Note that WS handling is enabled as default. This is part of the test.
#
language digits {

digit = [0-9].
entry file = digit+.

#
# Test: state variables
#
state {
	int digit_entry = 0;
	int digit_count = 0;
}

#
# Test: pre- and postactions
#
action digit 
pre: {
	digit_entry++;
}
post: {
	digit_count++;
}

#
# Test: No preaction, postaction only.
#
action file {
	Node result = current.set("Result");
	result.set("entry", "" + digit_entry);
	result.set("count", "" + digit_count);
}

}
